[[actions]]
name = "new from checked parents"
lua = '''
local args = { "new" }
for _, commit_id in ipairs(context.checked_commit_ids()) do
  table.insert(args, commit_id)
end
jj_async(args)
revisions.refresh()
'''

[[bindings]]
action = "new from checked parents"
key = "N"
scope = "revisions"
desc = "new from checked parents"
