EDITOR=nvim
VISUAL=nvim
SUDO_EDITOR=nvim
MANPAGER=nvim +Man!
OPENCODE_EXPERIMENTAL=true
MANROFFOPT=-c
VIRTUAL_ENV_DISABLE_PROMPT=1
FZF_DEFAULT_OPTS=--color=bg:-1,bg+:-1,preview-bg:-1,hl:underline,hl+:underline,fg:#cdd6f4,fg+:#cdd6f4,header:#b4befe,info:#b4befe,marker:#b4befe,pointer:#b4befe,prompt:#b4befe,spinner:#f5e0dc
PATH=${HOME}/.local/bin:${HOME}/.bun/bin:${HOME}/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
